"""
Django settings for EnvironmentalMeasurementProject project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5e!1cm-3#c8p-27)y&08g@=z9vjb0_wc$2f!b(15s3*92h&lq&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if DEBUG:
    # log_level = 'DEBUG'
    log_level = 'ERROR'
else:
    log_level = 'ERROR'
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TecrisDB.apps.TecrisdbConfig',
    'PublicDB.apps.PublicdbConfig',
    'MlitDB.apps.MlitdbConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EnvironmentalMeasurementProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EnvironmentalMeasurementProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'EnvironmentalMeasurementProjectDB',
        'USER': 'n_taguchi',
        'PASSWORD': 'uvqc0431',
        'HOST': '192.168.0.163',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,  # 追加
    },
    'TecrisDB': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'TecrisDB',
        'USER': 'n_taguchi',
        'PASSWORD': 'uvqc0431',
        'HOST': '192.168.0.163',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,  # 追加
    },
    'PublicDB': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'PublicDB',
        'USER': 'n_taguchi',
        'PASSWORD': 'uvqc0431',
        'HOST': '192.168.0.163',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,  # 追加
    },
    'MlitDB': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'MlitDB',
        'USER': 'n_taguchi',
        'PASSWORD': 'uvqc0431',
        'HOST': '192.168.0.163',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,  # 追加
    },
    'DamDB': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'DamDB',
        'USER': 'n_taguchi',
        'PASSWORD': 'uvqc0431',
        'HOST': '192.168.0.163',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,  # 追加
    },
    'RiverDB': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'RiverDB',
        'USER': 'n_taguchi',
        'PASSWORD': 'uvqc0431',
        'HOST': '192.168.0.163',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,  # 追加
    },
    'WisefDB': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'WisefDB',
        'USER': 'n_taguchi',
        'PASSWORD': 'uvqc0431',
        'HOST': '192.168.0.163',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,  # 追加
    },
}
DATABASE_ROUTERS = ['EnvironmentalMeasurementProject.db_router.EnvironmentalMeasurementProjectDBRouter',]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
# TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

from django.conf.global_settings import DATETIME_INPUT_FORMATS
DATETIME_INPUT_FORMATS += ('%Y/%m/%d',)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
