# Generated by Django 4.2.7 on 2023-11-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TecrisDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TecrisClassCode',
            new_name='TECRIS_CLASS_CODE',
        ),
        migrations.RenameModel(
            old_name='TecrisRiverTypeCode',
            new_name='TECRIS_RIVER_TYPE_CODE',
        ),
        migrations.RenameModel(
            old_name='TecrisWaterSystemCode',
            new_name='TECRIS_WATER_SYSTEM_CODE',
        ),
    ]
