# Generated by Django 4.2.7 on 2023-11-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRegimeCodePublic',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='流況コード（公共用水域及び地下水の水質測定計画）')),
                ('flow_regime', models.CharField(max_length=48, verbose_name='流況')),
            ],
            options={
                'verbose_name': '流況コード（公共用水域及び地下水の水質測定計画））',
                'verbose_name_plural': '流況コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
        migrations.CreateModel(
            name='OdorCodePublic',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='臭気コード（公共用水域及び地下水の水質測定計画）')),
                ('odor', models.CharField(max_length=24, verbose_name='臭気')),
            ],
            options={
                'verbose_name': '臭気コード（公共用水域及び地下水の水質測定計画）',
                'verbose_name_plural': '臭気コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
        migrations.CreateModel(
            name='SurveyClassCodePublic',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='調査区分コード（公共用水域及び地下水の水質測定計画）')),
                ('classification', models.CharField(max_length=24, verbose_name='調査区分')),
            ],
            options={
                'verbose_name': '調査区分コード（公共用水域及び地下水の水質測定計画）',
                'verbose_name_plural': '調査区分コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
        migrations.CreateModel(
            name='SurveyPositionCodePublic',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='採取位置コード（公共用水域及び地下水の水質測定計画）')),
                ('position', models.CharField(max_length=16, verbose_name='採取位置')),
            ],
            options={
                'verbose_name': '採取位置コード（公共用水域及び地下水の水質測定計画）',
                'verbose_name_plural': '採取位置コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
        migrations.CreateModel(
            name='WaterColorCodePublic',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='色相コード（公共用水域及び地下水の水質測定計画）')),
                ('color', models.CharField(max_length=24, verbose_name='色相')),
            ],
            options={
                'verbose_name': '色相コード（公共用水域及び地下水の水質測定計画）',
                'verbose_name_plural': '色相コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
        migrations.CreateModel(
            name='WaterSystemClassCodePublic',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='区分コード（公共用水域及び地下水の水質測定計画）')),
                ('classification', models.CharField(max_length=16, verbose_name='水系区分')),
            ],
            options={
                'verbose_name': '区分コード（公共用水域及び地下水の水質測定計画）',
                'verbose_name_plural': '区分コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
        migrations.CreateModel(
            name='WeatherCodePublic',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='天候コード（公共用水域及び地下水の水質測定計画）')),
                ('weather', models.CharField(max_length=16, verbose_name='天候')),
            ],
            options={
                'verbose_name': '天候コード（公共用水域及び地下水の水質測定計画）',
                'verbose_name_plural': '天候コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
        migrations.CreateModel(
            name='WindDirectionCodePublic',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='風向コード（公共用水域及び地下水の水質測定計画）')),
                ('wind_direction', models.CharField(max_length=8, verbose_name='風向')),
            ],
            options={
                'verbose_name': '風向コード（公共用水域及び地下水の水質測定計画）',
                'verbose_name_plural': '風向コード（公共用水域及び地下水の水質測定計画）',
            },
        ),
    ]
