# Generated by Django 4.2.7 on 2023-11-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlowRegimeCodePublic',
            new_name='FLOW_REGIME_CODE_PUBLIC',
        ),
        migrations.RenameModel(
            old_name='OdorCodePublic',
            new_name='ODOR_CODE_PUBLIC',
        ),
        migrations.RenameModel(
            old_name='SurveyClassCodePublic',
            new_name='SURVEY_CLASS_CODE_PUBLIC',
        ),
        migrations.RenameModel(
            old_name='SurveyPositionCodePublic',
            new_name='SURVEY_POSITION_CODE_PUBLIC',
        ),
        migrations.RenameModel(
            old_name='WaterColorCodePublic',
            new_name='WATER_COLOR_CODE_PUBLIC',
        ),
        migrations.RenameModel(
            old_name='WaterSystemClassCodePublic',
            new_name='WATER_SYSTEM_CLASS_CODE_PUBLIC',
        ),
        migrations.RenameModel(
            old_name='WeatherCodePublic',
            new_name='WEATHER_CODE_PUBLIC',
        ),
        migrations.RenameModel(
            old_name='WindDirectionCodePublic',
            new_name='WIND_DIRECTION_CODE_PUBLIC',
        ),
    ]
